name: 'Setup Rust Environment'
description: 'Composite action to setup Rust build environment with caching and Protoc'
runs:
  using: "composite"
  steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up cargo cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Display Rust version
      shell: bash
      run: |
        echo "::notice::Rust version: $(rustc --version)"
        echo "::notice::Cargo version: $(cargo --version)"
