name: Bugs
description: Found a bug? Report it here!
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: |
        Example: When I try to execute a swap transaction, the application crashes immediately after clicking the 'Swap' button.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to help someone else reproduce the problem.
      placeholder: |
        Example:
        1. Navigate to the swap interface
        2. Select SOL as input token
        3. Select USDC as output token
        4. Enter amount: 1.0 SOL
        5. Click 'Swap' button
        6. Observe the crash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: |
        Example: The swap transaction should be submitted successfully and I should see a confirmation message with the transaction signature.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Information about your environment (OS, browser, version, etc.)
      placeholder: |
        Example:
        - OS: Ubuntu 22.04 / Windows 11 / macOS 14.2
        - Browser: Chrome 120.0 / Firefox 121.0 / Safari 17.2
        - Application Version: v0.4.2
        - Rust Version: 1.75.0 (if applicable)
        - Node Version: 20.10.0 (if applicable)
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other notes, screenshots, logs, or error messages about your bug.
      placeholder: |
        Example:
        - Console error logs
        - Stack traces
        - Screenshots showing the issue
        - Related error messages
        - Workarounds you've tried
    validations:
      required: false
