name: Rust CI

on:
  push:
  pull_request:

# Cancel in-progress workflows on branches, except main.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        directory: ["./listen-legacy", "./listen-kit"]
    steps:
      - name: Setup Rust environment
        uses: ./.github/actions/rust-setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Lint
        working-directory: ${{ matrix.directory }}
        run: |
          echo "::notice::Running clippy in ${{ matrix.directory }}"
          cargo clippy --all-targets --all-features -- -D warnings
  
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        directory: ["./listen-legacy", "./listen-kit"]
    steps:
      - name: Setup Rust environment
        uses: ./.github/actions/rust-setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build
        working-directory: ${{ matrix.directory }}
        run: |
          echo "::notice::Building project in ${{ matrix.directory }}"
          cargo build --verbose

  test:
    runs-on: ubuntu-22.04
    needs: build
    strategy:
      fail-fast: false
      matrix:
        directory: ["./listen-legacy", "./listen-kit"]
    steps:
      - name: Setup Rust environment
        uses: ./.github/actions/rust-setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run tests
        working-directory: ${{ matrix.directory }}
        run: |
          echo "::notice::Running tests in ${{ matrix.directory }}"
          cargo test --lib --verbose
